feat(config): add config validation
I ran into an issue where I accidentally had duplicate window names
within a single session (I had copied one to make another window but
forgot to change the name). This resulted in a really annoying panic.

After these changes you'd get an actually "pretty good" error message:

```
Error: Configuration validation failed
Config file: /Users/rjackson/.config/binutils/local.config.lua

Issues found:
- Duplicate window name 'dotvim' found in session 'dotfiles' at indices 0 and 1
```

This also allows us to start adding more checks / validations for other
config values in the future.